[0m18:01:16.844191 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109042480>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1096f6a20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1096f6780>]}


============================== 18:01:16.847844 | 33fa8d50-eef2-4870-9f38-387e8aef35f6 ==============================
[0m18:01:16.847844 [info ] [MainThread]: Running with dbt=1.9.6
[0m18:01:16.848171 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/giovanistefani/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init datafinance_edw', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:01:16.858341 [debug] [MainThread]: Starter project path: /Users/giovanistefani/git/datafinance-dbt/datafinance/lib/python3.12/site-packages/dbt/include/starter_project
[0m18:01:16.863199 [info ] [MainThread]: 
Your new dbt project "datafinance_edw" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:01:16.863454 [info ] [MainThread]: Setting up your profile.
[0m18:01:29.370849 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 12.572737, "process_in_blocks": "0", "process_kernel_time": 0.172042, "process_mem_max_rss": "101924864", "process_out_blocks": "0", "process_user_time": 0.853307}
[0m18:01:29.371269 [debug] [MainThread]: Command `dbt init` succeeded at 18:01:29.371193 after 12.57 seconds
[0m18:01:29.371512 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1094bd400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1097dc230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109042480>]}
[0m18:01:29.371750 [debug] [MainThread]: Flushing usage events
[0m18:01:30.209675 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:03:40.441990 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1094ddee0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a3fac90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a3fa930>]}


============================== 12:03:40.445025 | 80215d6b-b5ed-477b-991a-922b3105e5f1 ==============================
[0m12:03:40.445025 [info ] [MainThread]: Running with dbt=1.9.6
[0m12:03:40.445341 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/giovanistefani/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run --select stg_unoserv', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:03:40.445631 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/giovanistefani/git/datafinance-dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:03:40.474823 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.0730385, "process_in_blocks": "0", "process_kernel_time": 0.145438, "process_mem_max_rss": "98336768", "process_out_blocks": "0", "process_user_time": 0.721119}
[0m12:03:40.475281 [debug] [MainThread]: Command `dbt run` failed at 12:03:40.475213 after 0.07 seconds
[0m12:03:40.475560 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10969fd40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a235a60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1094ddee0>]}
[0m12:03:40.475793 [debug] [MainThread]: Flushing usage events
[0m12:03:41.341445 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m08:12:54.463167 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10636dc40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f32e10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f32ba0>]}


============================== 08:12:54.466304 | e08acdd4-6122-429f-ab77-8247bdb21ab9 ==============================
[0m08:12:54.466304 [info ] [MainThread]: Running with dbt=1.9.6
[0m08:12:54.466628 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/giovanistefani/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run --select stg_unoserv', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m08:12:54.466929 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/giovanistefani/git/datafinance-dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m08:12:54.495027 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.07449708, "process_in_blocks": "0", "process_kernel_time": 0.146202, "process_mem_max_rss": "98402304", "process_out_blocks": "0", "process_user_time": 0.721363}
[0m08:12:54.495456 [debug] [MainThread]: Command `dbt run` failed at 08:12:54.495394 after 0.08 seconds
[0m08:12:54.495688 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106eec740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10636dc40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f32c60>]}
[0m08:12:54.495899 [debug] [MainThread]: Flushing usage events
[0m08:12:55.342329 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m08:15:31.524359 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10450ce00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1049eee70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1049eebd0>]}


============================== 08:15:31.527653 | 90ca012d-9089-4757-9c24-9dd5be69d3f9 ==============================
[0m08:15:31.527653 [info ] [MainThread]: Running with dbt=1.9.6
[0m08:15:31.527977 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/giovanistefani/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run --select stg_unoserv', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m08:15:31.528305 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/giovanistefani/git/datafinance-dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m08:15:31.530441 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.045877833, "process_in_blocks": "0", "process_kernel_time": 0.121896, "process_mem_max_rss": "96616448", "process_out_blocks": "0", "process_user_time": 0.675174}
[0m08:15:31.530742 [debug] [MainThread]: Command `dbt run` failed at 08:15:31.530686 after 0.05 seconds
[0m08:15:31.530936 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1049a89b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1049a8830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1049eeb70>]}
[0m08:15:31.531108 [debug] [MainThread]: Flushing usage events
[0m08:15:32.296693 [debug] [MainThread]: An error was encountered while trying to flush usage events
